### ISSUE TITLE
Using multiscale training strategy with Plus_Ultra.yaml dataset configuration

### ISSUE THREAD

**Issue by mingheyuemankong** [plemeri/InSPyReNet#53] opened 2024-08-23 11:36 UTC
Hello, the performance of the model in Plus_Ultra.yaml condition is now very good. 

However, I noticed that in Plus_Ultra.yaml, you are using multiple low- and high-resolution datasets and uniformly resize them to [1024,1024] during training.

I would like to ask you if you have considered adding a multi-scale training strategy during training to further improve the model's performance on images with multiple resolutions? For example, in a single batch, randomly select from [384, 512, 640,768, 1024, 1280] or even more scales, resize the image to the selected size, and then feed it into the network for training.

(1) Is this feasible without altering the existing inspyrenet network structure? 
(2) Is it possible to further improve the performance of the model in real scenes?

**Comment by crapthings** [comment] 2024-11-02 02:52
something like aspect ratio bucketing?

**Comment by plemeri** [comment] 2024-12-19 08:09
Duplicate of #44

**Closed by plemeri** 2024-12-19 08:09 UTC
Labels: duplicate
